<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '$' => '$',
    '<i class="fa fa-eraser"></i> Clean' => '<i class="fa fa-eraser"></i> Очистить',
    '<i class="fa fa-filter"></i> Filter' => '<i class="fa fa-filter"></i> Фильтр',
    'Accomplishment' => 'Достижение',
    'Account' => 'Профиль',
    'Additional' => 'Дополнительно',
    'All' => 'Все',
    'Annual Performance' => 'Годовой отчёт',
    'Are you sure you want to delete?' => '',
    'Attach' => 'Прикрепить',
    'Basic Information' => 'Общая информация',
    'Brazilian Portuguese' => '',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Category successfully deleted' => 'Категория удалена',
    'Category successfully included' => '',
    'Category updated' => 'Категория обновлена',
    'Changed' => 'Изменено',
    'Color' => 'Цвет',
    'Create' => 'Создать',
    'Create an account' => 'Создать профиль',
    'Create category' => 'Создать категорию',
    'Created' => 'Создано',
    'Current Month' => 'Текущий месяц',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Descrição' => '',
    'E-mail / Username' => 'Почта / имя пользователя',
    'English USA' => '',
    'Entries' => 'Записи',
    'Entry' => 'Запись',
    'Entry successfully deleted' => 'Запись удалена',
    'Entry successfully included' => '',
    'Entry updated' => 'Запись обновлена',
    'Expense' => 'Расход',
    'File' => 'Файл',
    'Filename' => 'Имя файла',
    'Filters' => 'Фильтры',
    'From' => 'От',
    'Hex Cor' => '',
    'ID' => 'ID',
    'Icon' => '',
    'Login to access the System' => 'Войдите для доступа к системе',
    'Monthly Comparative Revenue x Expense' => '',
    'Monthly Summary' => 'Месячный отчёт',
    'Monthly balance' => 'Месячный баланс',
    'Negative' => 'Отрицательный',
    'New Entry' => 'Новая запись',
    'No' => 'Нет',
    'No entries found!' => 'Записи не найдены!',
    'Options' => 'Настройки',
    'Overview' => 'Обзор',
    'Password' => '',
    'Pending' => 'Ожидается',
    'Percentage' => 'Проценты',
    'Performance' => 'Производительность',
    'Positive' => 'Положительный',
    'Previous Month' => 'Предыдущий месяц',
    'Profile' => 'Профиль',
    'Receipt' => 'Чек',
    'Reset' => 'Сбросить',
    'Revenue' => 'Прибыль',
    'Revenue x Expenses' => '',
    'Russian' => '',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Select' => 'Выбор',
    'Sign Out' => 'Выйти',
    'Targets' => 'Цели',
    'This category is associated with some record' => 'Данная категория используется в записях',
    'To' => 'До',
    'Track each category during the year' => '',
    'Type' => 'Тип',
    'Update' => 'Обновить',
    'Update Entry' => 'Обновить запись',
    'Value' => 'Значение',
    'Yes' => 'Да',
];
