<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Аккаунт',
    'Account has already been disabled' => 'Аккаунт уже был отвязан',
    'Account successfully disconnected' => 'Аккаунт успешно отвязан',
    'Account updated' => 'Аккаунт обновлен',
    'Bind account' => 'Подключить аккаунт',
    'Can not disconnect single authentication method. Please fill email and password and try again' => 'Нельзя отключить единственный метод аутентификации. Пожалуйста заполните email и пароль и попробуйте снова',
    'Cancel' => 'Отменить',
    'Changing your email requires email confirmation' => 'Изменение электронной почты требует подтверждения нового адреса',
    'Connected' => 'Подключен',
    'Create Time' => 'Дата создания',
    'Disconnect' => 'Отключен',
    'Forgot password' => 'Забыли пароль',
    'Full Name' => 'Полное имя',
    'Go home' => 'На главную',
    'Go to my account' => 'К моему аккаунту',
    'Guests can not disconnect accounts' => '',
    'ID' => 'Номер',
    'Invalid key' => 'Неверный ключ',
    'Keychain' => 'Ключница',
    'Language' => 'Язык',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => 'Подключение аккаунтов социальных сетей (можно несколько) к вашему аккаунту позволит выполнять вход в один клик.',
    'Log in here' => 'Войти сейчас',
    'Login' => 'Войти',
    'Password has been reset' => 'Пароль восстановлено',
    'Passwords do not match' => 'Пароли не совпадают',
    'Pending email confirmation: [ {newEmail} ]' => 'В ожидании подтверждения по электронной почте: [ {newEmail} ]',
    'Please fill out the following fields to register:' => 'Пожалуйста, заполните следующие поля для регистрации:',
    'Profile' => 'Профиль',
    'Register' => 'Зарегистрироваться',
    'Resend' => 'Повторить',
    'Reset' => 'Сбросить',
    'Start Page' => '',
    'Submit' => 'Отправить',
    'This account has already been connected' => 'Этот аккаунт уже был подключен',
    'Update' => 'Обновить',
    'Update Time' => 'Дата обновления',
    'User ID' => 'Номер пользователя',
    'Yii 2 User' => 'Yii 2 пользователь',
    'Your email [ {email} ] has been confirmed' => 'Ваш адрес электронной почты [ {email} ] было подтверждено',
    'or' => 'или',
    '{attribute} can contain only letters, numbers, and "_"' => '{attribute} может содержать только буквы, цифры и "_"',
    'Сan not disconnect a foreign account' => 'Нельзя отключить чужой аккаунт',
];
