<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Аккаунт',
    'Account has already been disabled' => 'Аккаунт уже был отвязан',
    'Account successfully disconnected' => 'Аккаунт успешно отвязан',
    'Account updated' => 'Аккаунт обновлен',
    'Bind account' => 'Подключить аккаунт',
    'Can not disconnect single authentication method. Please fill email and password and try again' => 'Нельзя отключить единственный метод аутентификации. Пожалуйста заполните email и пароль и попробуйте снова',
    'Cancel' => 'Отменить',
    'Changing your email requires email confirmation' => 'Изменение электронной почты требует подтверждения нового адреса',
    'Connected' => 'Подключен',
    'Create Time' => 'Дата создания',
    'Disconnect' => 'Отключен',
    'Forgot password' => 'Забыли пароль',
    'Full Name' => 'Полное имя',
    'Go home' => 'На главную',
    'Go to my account' => 'К моему аккаунту',
    'Guests can not disconnect accounts' => '',
    'ID' => 'Номер',
    'Invalid key' => 'Неверный ключ',
    'Keychain' => 'Ключница',
    'Language' => 'Язык',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => 'Подключение аккаунтов социальных сетей (можно несколько) к вашему аккаунту позволит выполнять вход в один клик.',
    'Log in here' => 'Войти сейчас',
    'Login' => 'Войти',
    'Password has been reset' => 'Пароль восстановлено',
    'Passwords do not match' => 'Пароли не совпадают',
    'Pending email confirmation: [ {newEmail} ]' => 'В ожидании подтверждения по электронной почте: [ {newEmail} ]',
    'Please fill out the following fields to register:' => 'Пожалуйста, заполните следующие поля для регистрации:',
    'Profile' => 'Профиль',
    'Register' => 'Зарегистрироваться',
    'Resend' => 'Повторить',
    'Reset' => 'Сбросить',
    'Submit' => 'Отправить',
    'This account has already been connected' => 'Этот аккаунт уже был подключен',
    'Update' => 'Обновить',
    'Update Time' => 'Дата обновления',
    'User ID' => 'Номер пользователя',
    'Yii 2 User' => 'Yii 2 пользователь',
    'Your email [ {email} ] has been confirmed' => 'Ваш адрес электронной почты [ {email} ] было подтверждено',
    'or' => 'или',
    '{attribute} can contain only letters, numbers, and "_"' => '{attribute} может содержать только буквы, цифры и "_"',
    'Сan not disconnect a foreign account' => 'Нельзя отключить чужой аккаунт',

    //yii2-user
    // models
    'ID' => 'Номер',
    'User ID' => 'Номер пользователя',
    'Create Time' => 'Дата создания',
    'Update Time' => 'Дата обновления',
    'Full Name' => 'Полное имя',
    'Language' => 'Язык',

    'Name' => 'Имя',
    'Can Admin' => 'Имеет права админа',

    'Role' => 'Роль',
    'Role ID' => 'Номер роли',
    'Status' => 'Статус',
    'Email' => 'E-mail адрес',
    'New Email' => 'Новый E-mail адрес',
    'Username' => 'Логин пользователя',
    'Password' => 'Пароль',
    'Auth Key' => 'Ключ авторизации',
    'Api Key' => 'Ключ API',
    'Login Ip' => 'IP авторизации',
    'Login Time' => 'Дата авторизации',
    'Create Ip' => 'IP создания',
    'Ban Time' => 'Дата бана',
    'Ban Reason' => 'Причина бана',
    'Current Password' => 'Текущий пароль',
    'New Password' => 'Новый пароль',
//    'New Password Confirm' => '',
    'Email Confirmation' => 'E-mail подтверждение',

    'Provider' => 'Приглашение',
    'Provider ID' => 'Номер пользователя который пригласил',
    'Provider Attributes' => 'Атрибуты приглашения',

    'Type' => 'Тип',
    'Key' => 'Ключ',
    'Consume Time' => 'Дата получения',
    'Expire Time' => 'Срок действия',

    // models/forms
    'Email not found' => 'E-mail не найдено',
    'Email / Username' => 'E-mail / имя пользователя',
    'Email / Username not found' => 'E-mail / имя пользователя не найдено',
    'Username not found' => 'Пользователь не найден',
    'User is banned - {banReason}' => 'Пользователя блокировано - {banReason}',
    'Incorrect password' => 'Неверный пароль',
    'Remember Me' => 'Запомнить меня',
    'Email is already active' => 'E-mail уже активен',
//    'Passwords do not match' => '',
//    '{attribute} can contain only letters, numbers, and "_"' => '',

    // controllers
    'Successfully registered [ {displayName} ]' => 'Успешно зарегистрирован [ {displayName} ]',
    ' - Please check your email to confirm your account' => ' - Проверьте свою почту, чтобы подтвердить свой ​​аккаунт',
    'Account updated' => 'Аккаунт обновлен',
    'Profile updated' => 'Профиль обновлен',
    'Confirmation email resent' => 'Подтверждение по электронной почте отправлено заново',
    'Email change cancelled' => 'Изменение E-mail отменено',
    'Instructions to reset your password have been sent' => 'Инструкции по изменению вашего пароля, были отправлены в ваш почтовый ящик',

    // mail
    'Please confirm your email address by clicking the link below:' => 'Пожалуйста, подтвердите свой ​​адрес электронной почты, нажав на ссылку ниже:',
    'Please use this link to reset your password:' => 'Пожалуйста, воспользуйтесь этой ссылкой для восстановления пароля:',

    // admin views
    'Users' => 'Пользователи',
    'Banned' => 'Заблокировано',
    'Create' => 'Создано',
    'Update' => 'Обновить',
    'Delete' => 'Удалено',
    'Search' => 'Поиск',
    'Reset' => 'Сбросить',
    'Create {modelClass}' => 'Создать {modelClass}',
    'Update {modelClass}: ' => 'Изменить {modelClass}: ',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить ваш аккаунт?',

    // default views
    'Account' => 'Аккаунт',
    'Pending email confirmation: [ {newEmail} ]' => 'В ожидании подтверждения по электронной почте: [ {newEmail} ]',
    'Cancel' => 'Отменить',
    'Changing your email requires email confirmation' => 'Изменение электронной почты требует подтверждения нового адреса',
    'Confirmed' => 'Подтверждено',
    'Error' => 'Ошибка',
    'Your email [ {email} ] has been confirmed' => 'Ваш адрес электронной почты [ {email} ] было подтверждено',
    'Go to my account' => 'К моему аккаунту',
    'Go home' => 'На главную',
    'Log in here' => 'Войти сейчас',
    'Invalid key' => 'Неверный ключ',
    'Forgot password' => 'Забыли пароль',
    'Submit' => 'Отправить',
    'Yii 2 User' => 'Yii 2 пользователь',
    'Login' => 'Войти',
    'Register' => 'Зарегистрироваться',
    'Logout' => 'Выйти',
    'Resend confirmation email' => 'Повторно отправить подтверждение по электронной почте',
    'Profile' => 'Профиль',
    'Please fill out the following fields to login:' => 'Пожалуйста, заполните следующие поля для входа:',
    'Please fill out the following fields to register:' => 'Пожалуйста, заполните следующие поля для регистрации:',
    'Resend' => 'Повторить',
    'Password has been reset' => 'Пароль восстановлено',
];
