<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '$' => '',
    '<i class="fa fa-eraser"></i> Clean' => '',
    '<i class="fa fa-filter"></i> Filter' => '',
    'Accomplishment' => '',
    'Account' => '',
    'Additional' => '',
    'All' => '',
    'Annual Performance' => '',
    'Are you sure you want to delete?' => '',
    'Attach' => '',
    'Basic Information' => '',
    'Brazilian Portuguese' => '',
    'Categories' => '',
    'Category' => '',
    'Category successfully deleted' => '',
    'Category successfully included' => '',
    'Category updated' => '',
    'Changed' => '',
    'Color' => '',
    'Create' => '',
    'Create an account' => '',
    'Create category' => '',
    'Created' => '',
    'Current Month' => '',
    'Date' => '',
    'Delete' => '',
    'Description' => '',
    'Descrição' => '',
    'E-mail / Username' => '',
    'English USA' => '',
    'Entries' => '',
    'Entry' => '',
    'Entry successfully deleted' => '',
    'Entry successfully included' => '',
    'Entry updated' => '',
    'Expense' => '',
    'File' => '',
    'Filename' => '',
    'Filters' => '',
    'From' => '',
    'Hex Cor' => '',
    'ID' => '',
    'Icon' => '',
    'Login to access the System' => '',
    'Monthly Comparative Revenue x Expense' => '',
    'Monthly Summary' => '',
    'Monthly balance' => '',
    'Negative' => '',
    'New Entry' => '',
    'No' => '',
    'No entries found!' => '',
    'Options' => '',
    'Overview' => '',
    'Pending' => '',
    'Percentage' => '',
    'Performance' => '',
    'Positive' => '',
    'Previous Month' => '',
    'Profile' => '',
    'Receipt' => '',
    'Reset' => '',
    'Revenue' => '',
    'Revenue x Expenses' => '',
    'Russian' => '',
    'Save' => '',
    'Search' => '',
    'Select' => '',
    'Sign Out' => '',
    'Targets' => '',
    'Are you sure you want to delete?' => '',
    'This category is associated with some record' => '',
    'To' => '',
    'Track each category during the year' => '',
    'Type' => '',
    'Update' => '',
    'Update Entry' => '',
    'Value' => '',
    'Yes' => '',
];
