<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Cuenta',
    'Account has already been disabled' => '',
    'Account successfully disconnected' => '',
    'Account updated' => 'Cuenta modificada',
    'Bind account' => '',
    'Can not disconnect single authentication method. Please fill email and password and try again' => '',
    'Cancel' => 'Cancelar',
    'Changing your email requires email confirmation' => 'Cambiar tu dirección de correo requiere confirmación',
    'Connected' => '',
    'Create Time' => 'Fecha de Creación',
    'Disconnect' => '',
    'Forgot password' => 'Contraseña olvidada',
    'Full Name' => 'Nombre completo',
    'Go home' => 'Inicio',
    'Go to my account' => 'Ir a mi cuenta',
    'Guests can not disconnect accounts' => '',
    'ID' => 'Código',
    'Invalid key' => 'Key inválida',
    'Keychain' => '',
    'Language' => 'Idioma',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => '',
    'Log in here' => 'Iniciar sesión',
    'Login' => 'Entrar',
    'Password has been reset' => 'La contraseña ha sido reiniciada',
    'Passwords do not match' => 'Las contraseñas no coinciden',
    'Pending email confirmation: [ {newEmail} ]' => 'Confirmación de correo pendiente: [ {newEmail} ]',
    'Profile' => 'Perfil',
    'Register' => 'Registro',
    'Resend' => 'Reenviar',
    'Reset' => 'Reiniciar',
    'Start Page' => '',
    'Submit' => 'Enviar',
    'This account has already been connected' => '',
    'Update' => 'Actualizar',
    'Update Time' => 'Fecha de Actualización',
    'User ID' => 'Código de Usuario',
    'Yii 2 User' => 'Usuario de Yii 2',
    'Your email [ {email} ] has been confirmed' => 'Tu dirección de correo [ {email} ] ha sido confirmada',
    'or' => '',
    '{attribute} can contain only letters, numbers, and "_"' => '{attribute} puede contener tan solo letras, números y "_"',
    'Сan not disconnect a foreign account' => '',
];
