<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Cuenta',
    'Account has already been disabled' => '',
    'Account successfully disconnected' => '',
    'Account updated' => 'Cuenta modificada',
    'Bind account' => '',
    'Can not disconnect single authentication method. Please fill email and password and try again' => '',
    'Cancel' => 'Cancelar',
    'Changing your email requires email confirmation' => 'Cambiar tu dirección de correo requiere confirmación',
    'Connected' => '',
    'Create Time' => 'Fecha de Creación',
    'Disconnect' => '',
    'Forgot password' => 'Contraseña olvidada',
    'Full Name' => 'Nombre completo',
    'Go home' => 'Inicio',
    'Go to my account' => 'Ir a mi cuenta',
    'Guests can not disconnect accounts' => '',
    'ID' => 'Código',
    'Invalid key' => 'Key inválida',
    'Keychain' => '',
    'Language' => 'Idioma',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => '',
    'Log in here' => 'Iniciar sesión',
    'Login' => 'Entrar',
    'Password has been reset' => 'La contraseña ha sido reiniciada',
    'Passwords do not match' => 'Las contraseñas no coinciden',
    'Pending email confirmation: [ {newEmail} ]' => 'Confirmación de correo pendiente: [ {newEmail} ]',
    'Please fill out the following fields to register:' => 'Por favor rellena los siguientes campos para poder registrarte:',
    'Profile' => 'Perfil',
    'Register' => 'Registro',
    'Resend' => 'Reenviar',
    'Reset' => 'Reiniciar',
    'Submit' => 'Enviar',
    'This account has already been connected' => '',
    'Update' => 'Actualizar',
    'Update Time' => 'Fecha de Actualización',
    'User ID' => 'Código de Usuario',
    'Yii 2 User' => 'Usuario de Yii 2',
    'Your email [ {email} ] has been confirmed' => 'Tu dirección de correo [ {email} ] ha sido confirmada',
    'or' => '',
    '{attribute} can contain only letters, numbers, and "_"' => '{attribute} puede contener tan solo letras, números y "_"',
    'Сan not disconnect a foreign account' => '',

    //yii2-auth
    // models
    'ID' => 'Código',
    'User ID' => 'Código de Usuario',
    'Create Time' => 'Fecha de Creación',
    'Update Time' => 'Fecha de Actualización',
    'Full Name' => 'Nombre completo',
    'Language' => 'Idioma',

    'Name' => 'Nombre',
    'Can Admin' => 'Puede Administrar',

    'Role' => 'Rol',
    'Role ID' => 'Código de Rol',
    'Status' => 'Estado',
    'Email' => 'Correo elecrónico',
    'New Email' => 'Nuevo correo electrónico',
    'Username' => 'Nombre de Usuario',
    'Password' => 'Contraseña',
    'Auth Key' => 'Clave de Autorización',
    'Api Key' => 'Clave de la API',
    'Login Ip' => 'IP de Conexión',
    'Login Time' => 'Fecha de Conexión',
    'Create Ip' => 'IP de Creación',
    'Ban Time' => 'Tiempo de Expulsión',
    'Ban Reason' => 'Razón de Expulsión',
    'Current Password' => 'Contraseña Actual',
    'New Password' => 'Nueva Contraseña',
    'New Password Confirm' => 'Confirmación de nueva contraseña',
    'Email Confirmation' => 'Confirmación de correo',

    'Provider' => 'Proveedor',
    'Provider ID' => 'Código de proveedor',
    'Provider Attributes' => 'Atributos de proveedor',

    'Type' => 'Tipo',
    'Key' => 'Clave',
    'Consume Time' => 'Fecha de Consumición',
    'Expire Time' => 'Fecha de Expiración',

    // models/forms
    'Email not found' => 'Correo no encontrado',
    'Email / Username' => 'Correo / Usuario',
    'Email / Username not found' => 'Correo / Usuario no encontrado',
    'Username not found' => 'Usuario no encontrado',
    'User is banned - {banReason}' => 'El usuario está expulsado - {banReason}',
    'Incorrect password' => 'Contraseña incorrecta',
    'Remember Me' => 'Recuérdame',
    'Email is already active' => 'El correo ya está activo',
    'Passwords do not match' => 'Las contraseñas no coinciden',
    '{attribute} can contain only letters, numbers, and "_"' => '{attribute} puede contener tan solo letras, números y "_"',

    // controllers
    'Successfully registered [ {displayName} ]' => 'Registrado con éxito [ {displayName} ]',
    ' - Please check your email to confirm your account' => ' - Por favor, comprueba tu correo para confirmar el registro',
    'Account updated' => 'Cuenta modificada',
    'Profile updated' => 'Perfil modificado',
    'Confirmation email resent' => 'Correo de confirmación reenviado',
    'Email change cancelled' => 'Cambio de correo cancelado',
    'Instructions to reset your password have been sent' => 'Las instrucciones para reiniciar tu contraseña han sido enviadas',

    // mail
    'Please confirm your email address by clicking the link below:' => 'Por favor, confirma tu dirección de correo haciendo click en el enlace de abajo:',
    'Please use this link to reset your password:' => 'Por favor, usa este link para reiniciar tu contraseña:',

    // admin views
    'Users' => 'Usuarios',
    'Banned' => 'Expulsado',
    'Create' => 'Crear',
    'Update' => 'Actualizar',
    'Delete' => 'Eliminar',
    'Search' => 'Búsqueda',
    'Reset' => 'Reiniciar',
    'Create {modelClass}' => 'Crear {modelClass}',
    'Update {modelClass}: ' => 'Actualizar {modelClass}: ',
    'Are you sure you want to delete this item?' => '¿Está seguro de que desea eliminar este elemento?',

    // default views
    'Account' => 'Cuenta',
    'Pending email confirmation: [ {newEmail} ]' => 'Confirmación de correo pendiente: [ {newEmail} ]',
    'Cancel' => 'Cancelar',
    'Changing your email requires email confirmation' => 'Cambiar tu dirección de correo requiere confirmación',
    'Confirmed' => 'Confirmado',
    'Error' => 'Error',
    'Your email [ {email} ] has been confirmed' => 'Tu dirección de correo [ {email} ] ha sido confirmada',
    'Go to my account' => 'Ir a mi cuenta',
    'Go home' => 'Inicio',
    'Log in here' => 'Iniciar sesión',
    'Invalid key' => 'Key inválida',
    'Forgot password' => 'Contraseña olvidada',
    'Submit' => 'Enviar',
    'Yii 2 User' => 'Usuario de Yii 2',
    'Login' => 'Entrar',
    'Register' => 'Registro',
    'Logout' => 'Salir', // i dont think this is used ...
    'Resend confirmation email' => 'Reenviar correo de confirmación',
    'Profile' => 'Perfil',
    'Please fill out the following fields to login:' => 'Por favor, rellena los siguientes campos para poder iniciar sesión:',
    'Please fill out the following fields to register:' => 'Por favor rellena los siguientes campos para poder registrarte:',
    'Resend' => 'Reenviar',
    'Password has been reset' => 'La contraseña ha sido reiniciada',
];
