<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account has already been disabled' => 'Paskyra jau išjungta',
    'Account successfully disconnected' => 'Paskyra sėkmingai išjungta',
    'Account updated' => 'Paskyra atnaujinta',
    'Bind account' => 'Susieti paskyrą',
    'Can not disconnect single authentication method. Please fill email and password and try again' => 'Negalite išjungti vieno autentifikavimo metodo. Įveskite savo el. pašto adresą bei slaptažodį ir bandykite dar kartą.',
    'Cancel' => 'Atšaukti',
    'Changing your email requires email confirmation' => 'El. pašto pakeitimas reikalauja patvirtinimo',
    'Connected' => 'Prijungtas',
    'Create Time' => 'Sukųrimo data',
    'Disconnect' => 'Atsijungti',
    'Full Name' => 'Pilnas Vardas',
    'Go home' => 'Į pagrindinį',
    'Go to my account' => 'Į mano paskyrą',
    'Guests can not disconnect accounts' => 'Svečiai negali atjungti paskyrų',
    'ID' => 'ID',
    'Instructions to reset your password have been sent' => 'Slaptažodžio keitimo instrukcija išsiųsta',
    'Invalid key' => 'Neteisingas raktas',
    'Keychain' => 'Autentifikavimas',
    'Language' => 'Kalba',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => 'Prijungę socialinio tinklo paskyras (galite turėti keletą) prie savo paskyros, galėsite prisijungti vienu paspaudimu.',
    'Log in here' => 'Prisijungti čia',
    'Login' => 'Prisijungti',
    'Password has been reset' => 'Slaptažodis buvo nustatytas iš naujo',
    'Passwords do not match' => 'Slaptažodžiai nesutampa',
    'Pending email confirmation: [ {newEmail} ]' => 'Laukiamas patvirtinimas el. paštu: [ {newEmail} ]',
    'Profile' => 'Profilis',
    'Resend' => 'Siųsti dar kartą',
    'Reset' => 'Atstatyti',
    'Start Page' => 'Namų Puslapis',
    'Submit' => 'Pateikti',
    'This account has already been connected' => 'Ši paskyra jau buvo prijungta',
    'Update' => 'Atnaujinti',
    'Update Time' => 'Atnaujinimo laikas',
    'User ID' => 'Vartotojo ID',
    'Yii 2 User' => 'Yii 2 vartotojas',
    'Your email [ {email} ] has been confirmed' => 'Jūsų el. paštas [ {email} ] buvo patvirtintas',
    'or' => 'arba',
    '{attribute} can contain only letters, numbers, and "_"' => '{attribute} gali būti sudarytas iš raidžių, skaičių arba "_"',
    'Сan not disconnect a foreign account' => 'Negalima atjungti kitos paskyros',
];
