<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account has already been disabled' => 'Compte a déja été désactivé',
    'Account successfully disconnected' => 'Compte déconnecté avec succès',
    'Account updated' => 'Compte actualisé',
    'Bind account' => 'Compte lié',
    'Can not disconnect single authentication method. Please fill email and password and try again' => 'Ne peut pas déconnecter une méthode d\'authentification simple',
    'Cancel' => 'Abandonner',
    'Changing your email requires email confirmation' => 'Modifier votre email demande une confirmation par email',
    'Connected' => 'Connecté',
    'Create Time' => 'Date de création',
    'Disconnect' => 'Déconnecter',
    'Full Name' => 'Nom complet',
    'Go home' => 'Accueil',
    'Go to my account' => 'Aller sur mon compte',
    'Guests can not disconnect accounts' => 'Les invités ne peuvent pas déconnecter les comptes',
    'ID' => 'Código',
    'Instructions to reset your password have been sent' => 'Les instructions pour réinitialiser votre mot de passe ont été envoyés',
    'Invalid key' => 'clé non valide',
    'Keychain' => 'Touche d\'accès restreint',
    'Language' => 'Langage',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => 'Lier les comptes de réseaux sociaux (il peut y en avoir plusieurs) à votre compte ce qui vous permettra d\'entrer en un seul clic',
    'Log in here' => 'Connectez-vous ici',
    'Login' => 'Identifiant',
    'Password has been reset' => 'Le mot de passe a été réinitialisé',
    'Passwords do not match' => 'Les mots de passe ne correspondent pas',
    'Pending email confirmation: [ {newEmail} ]' => 'En attente de confirmation de l\'email: [ {newEmail} ]',
    'Profile' => 'Profil',
    'Resend' => 'Renvoie',
    'Reset' => 'Réinitialisation',
    'Start Page' => 'Page d\'accueil',
    'Submit' => 'Envoyer',
    'This account has already been connected' => 'Ce compte a été déconnecté',
    'Update' => 'Actualisation',
    'Update Time' => 'Date d\'actualisation',
    'User ID' => 'Code utilisateur',
    'Yii 2 User' => 'Utilisateur de Yii 2',
    'Your email [ {email} ] has been confirmed' => 'Votre email [ {email} ] a été confirmé',
    'or' => 'ou',
    '{attribute} can contain only letters, numbers, and "_"' => 'Doit contenir uniquement des lettres, nombres et , numeros e _',
    'Сan not disconnect a foreign account' => 'Ne peut pas déconnecter un compte étrangé',
];
