<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '$' => 'R$',
    '<i class="fa fa-eraser"></i> Clean' => '<i class="fa fa-eraser"></i> Limpar',
    '<i class="fa fa-filter"></i> Filter' => '<i class="fa fa-filter"></i> Filtrar',
    'Accomplishment' => 'Realização',
    'Account' => 'Minha Conta',
    'Additional' => 'Complementares',
    'All' => 'Todos',
    'Annual Performance' => 'Desempenho Anual',
    'Are you sure you want to delete?' => 'Tem certeza que deseja excluir?',
    'Attach' => 'Anexo',
    'Basic Information' => 'Informações Básicas',
    'Brazilian Portuguese' => 'Portugês Brasileiro',
    'Categories' => 'Categorias',
    'Category' => 'Categoria',
    'Category successfully deleted' => 'Categoria excluído com sucesso',
    'Category successfully included' => 'Categoria incluída com sucesso',
    'Category updated' => 'Categoria atualizada',
    'Changed' => 'Alterado',
    'Color' => 'Cor',
    'Create' => 'Novo',
    'Create an account' => 'Criar uma conta',
    'Create category' => 'Adicionar categoria',
    'Created' => 'Incluído',
    'Current Month' => 'Mês Atual',
    'Date' => 'Data',
    'Delete' => 'Excluir',
    'Description' => 'Descrição',
    'Descrição' => '',
    'E-mail / Username' => 'E-mail / Usuário',
    'English USA' => 'Inglês USA',
    'Entries' => 'Lançamentos',
    'Entry' => 'Lançamento',
    'Entry successfully deleted' => 'Lançamento excluído com sucesso',
    'Entry successfully included' => 'Lançamento incluído com sucesso',
    'Entry updated' => 'Lançamento atualizado',
    'Expense' => 'Despesa',
    'File' => 'Arquivo',
    'Filename' => 'Nome do Arquivo',
    'Filters' => 'Filtros',
    'From' => 'De',
    'Hex Cor' => '',
    'ID' => 'ID',
    'Icon' => 'Icone',
    'Login to access the System' => 'Autentique-se para acessar',
    'Monthly Comparative Revenue x Expense' => 'Comparativo mensal de Receita x Despesa',
    'Monthly Summary' => 'Resumo Mensal',
    'Monthly balance' => 'Saldo do mês',
    'Negative' => 'Negativo',
    'New Entry' => 'Novo Lançamento',
    'No' => 'Não',
    'No attachment' => '',
    'No entries found!' => 'Nenhum lançamento encontrado!',
    'Options' => 'Opções',
    'Overview' => 'Visão Geral',
    'Password' => 'Senha',
    'Pending' => 'Pendente',
    'Percentage' => 'Percentual',
    'Performance' => 'Desempenho',
    'Positive' => 'Positivo',
    'Previous Month' => 'Mês Anterior',
    'Profile' => 'Meu Perfil',
    'Receipt' => 'Comprovante',
    'Reset' => '',
    'Revenue' => 'Receita',
    'Revenue x Expenses' => 'Receita x Despesa',
    'Russian' => 'Russo',
    'Save' => 'Gravar',
    'Search' => '',
    'Select' => 'Selecione',
    'Sign Out' => 'Sair',
    'Targets' => 'Metas',
    'The page you requested is not available or does not exist.' => 'A página solicitada não está disponível ou não existe.',
    'This category is associated with some record' => 'Essa categoria está associada a algum registro',
    'To' => 'Até',
    'Track each category during the year' => 'Acompanhe cada categoria durante o ano',
    'Type' => 'Tipo',
    'Update' => 'Alterar',
    'Update Entry' => 'Alterar Lançamento',
    'Value' => 'Valor',
    'Yes' => 'Sim',
];
