<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Conta',
    'Cancel' => 'Cancelar',
    'Changing your email requires email confirmation' => 'Alterar o seu e-mail requer confirmação',
    'Forgot password' => 'Esqueceu sua senha',
    'Go home' => 'Ir para página inicial',
    'Go to my account' => 'Ir para a minha conta',
    'Invalid key' => 'Chave inválida',
    'Log in here' => 'Acesse',
    'Login' => 'Login',
    'Password has been reset' => 'A senha foi reiniciada',
    'Pending email confirmation: [ {newEmail} ]' => 'Confirmação de e-mail pendente: [ {newEmail} ]',
    'Please fill out the following fields to register:' => 'Por favor preencha os campos seguintes para se registrar:',
    'Profile' => 'Perfil',
    'Register' => 'Criar uma conta',
    'Resend' => 'Re-enviar',
    'Reset' => 'Reiniciar',
    'Submit' => 'Enviar',
    'Update' => 'Atualizar',
    'Yii 2 User' => 'Usuário do Yii 2',
    'Your email [ {email} ] has been confirmed' => 'O seu e-mail [ {email} ] foi confirmado',
];
