<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account has already been disabled' => 'Conta já foi desabilitada',
    'Account successfully disconnected' => 'Conta desconectada com sucesso',
    'Account updated' => 'Conta atualizada',
    'Bind account' => 'Vincular conta',
    'Can not disconnect single authentication method. Please fill email and password and try again' => 'Não é possível desconectar método de autenticação única. Por favor, preencha e-mail e senha e tente novamente',
    'Cancel' => 'Cancel',
    'Changing your email requires email confirmation' => 'Alterar o seu e-mail requer confirmação',
    'Connected' => 'Conectado',
    'Create Time' => 'Data de Criação',
    'Disconnect' => 'Desconectar',
    'Full Name' => 'Nome completo',
    'Go home' => 'Ir para página inicial',
    'Go to my account' => 'Ir para a minha conta',
    'Guests can not disconnect accounts' => 'Visitantes não podem desconectar contas',
    'ID' => 'Código',
    'Invalid key' => 'Chave inválida',
    'Keychain' => 'Chaves de Acesso Vinculadas',
    'Language' => 'Idioma',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => 'Vinculando contas de redes sociais (pode haver vários) para sua conta permitirá que você entrar em um único clique',
    'Log in here' => 'Entre aqui',
    'Login' => 'Entrar',
    'Password has been reset' => 'Senha reiniciada',
    'Passwords do not match' => '',
    'Pending email confirmation: [ {newEmail} ]' => 'Esperando confirmação do correio eletrónico: [ {newEmail} ]',
    'Profile' => 'Perfil',
    'Resend' => 'Reenviar',
    'Reset' => 'Reiniciar',
    'Start Page' => 'Pagina Inicial',
    'Submit' => 'Enviar',
    'This account has already been connected' => 'Essa conta já foi desconectada',
    'Update' => 'Atualizar',
    'Update Time' => 'Data de Atualização',
    'User ID' => 'Código de Utilizador',
    'Yii 2 User' => 'Utilizador de Yii 2',
    'Your email [ {email} ] has been confirmed' => 'O seu correio eletrónico [ {email} ] foi confirmado',
    'or' => 'ou',
    '{attribute} can contain only letters, numbers, and "_"' => 'Deve conter apenas letras, numeros e _',
    'Сan not disconnect a foreign account' => 'Não permitido desconectar conta',
];
