<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account has already been disabled' => 'El compte ja ha estat desactivat',
    'Account successfully disconnected' => 'El compte s\'ha desconnectat correctament',
    'Account updated' => 'Compte actualitzada',
    'Bind account' => 'Enllaçar compte',
    'Can not disconnect single authentication method. Please fill email and password and try again' => 'No es pot desconnectar un sol mètode d\'autenticació. Sisplau introdueix el correu electronic i la contrassenya i intenta-ho de nou',
    'Cancel' => 'Cancelar',
    'Changing your email requires email confirmation' => 'Canviar el correu electrònic requereix un correu de confirmació',
    'Connected' => 'Connectat',
    'Create Time' => 'Data de creació',
    'Disconnect' => 'Desconnectar',
    'Full Name' => 'Nom complet',
    'Go home' => 'Inici',
    'Go to my account' => 'El meu compte',
    'Guests can not disconnect accounts' => 'Els i les convidades no poden desconnectar comptes',
    'ID' => 'ID',
    'Instructions to reset your password have been sent' => 'S\'han enviat les instruccions per reiniciar la contrassenya',
    'Invalid key' => 'Clau incorrecta',
    'Keychain' => 'Clauer',
    'Language' => 'Idioma',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => 'Enllaçar comptes de xarxes socials al teu compte et permetrà accedir amb un sol clic',
    'Log in here' => 'Iniciar sessió',
    'Login' => 'Entrar',
    'Password has been reset' => 'La contrassenya ha estat reiniciada',
    'Passwords do not match' => 'Les contrassenyes no coincideixen',
    'Pending email confirmation: [ {newEmail} ]' => 'Confirmació de correu pendent: [ {newEmail} ]',
    'Profile' => 'Perfil',
    'Resend' => 'Reenviar',
    'Reset' => 'Reiniciar',
    'Start Page' => 'Pàgina d\'inici',
    'Submit' => 'Enviar',
    'This account has already been connected' => 'Aquest compte ja ha estat connectat',
    'Update' => 'Actualizar',
    'Update Time' => 'Data d\'actualització',
    'User ID' => 'Identificador d\'usuari',
    'Yii 2 User' => 'Usuario de Yii 2',
    'Your email [ {email} ] has been confirmed' => '
    El teu cosrreu electronic [ {email} ] s\'ha confirmat correctament',
    'or' => 'o',
    '{attribute} can contain only letters, numbers, and "_"' => '{attribute} només pot contenir lletres, números i "_"',
    'Сan not disconnect a foreign account' => 'No es pot desconnectar un compte aliè',
];
