<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account has already been disabled' => 'Benutzerkonto wurde bereits deaktiviert',
    'Account successfully disconnected' => 'Benutzerkonto erfolgreich getrennt',
    'Account updated' => 'Benutzerkonto aktualisiert',
    'Bind account' => 'Benutzerkonto verbinden',
    'Can not disconnect single authentication method. Please fill email and password and try again' => 'Einfache Authentifizierung kann nicht deaktiviert werden. Bitte email und passwort nochmals eingeben',
    'Cancel' => 'Abbrechen',
    'Changing your email requires email confirmation' => 'Ändern der Mailadresse erfordert Bestätigungsmail',
    'Connected' => 'Verbunden',
    'Create Time' => 'Erstellungsdatum',
    'Disconnect' => 'Verbindung trennen',
    'Full Name' => 'Vor- und Nachname',
    'Go home' => 'Startseite',
    'Go to my account' => 'zum Benutzerkonto wechseln',
    'Guests can not disconnect accounts' => 'Besucher können keine Benutzerkontos deaktivieren',
    'ID' => 'ID',
    'Instructions to reset your password have been sent' => 'Anweisungen um Passwort zurückzusetzen wurden versandt',
    'Invalid key' => 'ungültiger schlüssel',
    'Keychain' => 'Schlüsselbund',
    'Language' => 'Sprache',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => 'Konto mit Social-Media Benutzeraccount verknüpfen (mehrere möglich)',
    'Log in here' => 'Hier anmelden',
    'Login' => 'Login',
    'Password has been reset' => 'Passwort wurde zurückgesetzt',
    'Passwords do not match' => 'Passwort falsch',
    'Pending email confirmation: [ {newEmail} ]' => 'Email bestätigung ausstehend [{newEmail}]',
    'Profile' => 'Profil',
    'Resend' => 'nochmals versendet',
    'Reset' => 'zurücksetzten',
    'Start Page' => 'Startseite',
    'Submit' => 'Senden',
    'This account has already been connected' => 'Account bereits angemeldet',
    'Update' => 'Aktualisieren',
    'Update Time' => 'aktualisierungszeitpunkt',
    'User ID' => 'Benutzer ID',
    'Yii 2 User' => 'Yii 2 Benutzer',
    'Your email [ {email} ] has been confirmed' => 'Ihre email [ {email} ] wurde bestätigt',
    'or' => 'oder',
    '{attribute} can contain only letters, numbers, and "_"' => 'darf nur Buchstaben, Zahlen und "_" beinhalten',
    'Сan not disconnect a foreign account' => 'anderes Konto kann nicht entfernt werden',
];
