<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account has already been disabled' => '账号已被禁用',
    'Account successfully disconnected' => '账号已成功断开',
    'Account updated' => '账号已更新',
    'Bind account' => '绑定账号',
    'Can not disconnect single authentication method. Please fill email and password and try again' => '无法断开单点登录认证。请填写邮箱和密码，并重试',
    'Cancel' => '取消',
    'Changing your email requires email confirmation' => '更改您的邮箱地址需要邮件确认',
    'Connected' => '已连接',
    'Create Time' => '创建时间',
    'Disconnect' => '断开',
    'Full Name' => '全名',
    'Go home' => '返回主页',
    'Go to my account' => '进入我的账号',
    'Guests can not disconnect accounts' => '访客无法断开账号。',
    'ID' => 'ID',
    'Instructions to reset your password have been sent' => '重置您密码的指示已经发送',
    'Invalid key' => '无效的密钥',
    'Keychain' => '密钥链',
    'Language' => '语言',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => '关联社交网络账号（可以多个）到您的账号，将使您能够一键登录。',
    'Log in here' => '在这里登录',
    'Login' => '登录',
    'Password has been reset' => '密码已经重置',
    'Passwords do not match' => '密码不匹配',
    'Pending email confirmation: [ {newEmail} ]' => '邮件确认处理中：[ {newEmail} ]',
    'Profile' => '用户配置',
    'Resend' => '重新发送',
    'Reset' => '重置',
    'Start Page' => '开始页面',
    'Submit' => '提交',
    'This account has already been connected' => '该账号已经连接',
    'Update' => '更新',
    'Update Time' => '更新时间',
    'User ID' => '用户 ID',
    'Yii 2 User' => 'Yii 2 用户',
    'Your email [ {email} ] has been confirmed' => '您的邮箱地址[ {email} ]已确认',
    'or' => '或者',
    '{attribute} can contain only letters, numbers, and "_"' => '{attribute} 只能包含字母，数据和下划线',
    'Сan not disconnect a foreign account' => '无法断开外来账号',
];
