<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account has already been disabled' => 'A fiók már le van tiltva',
    'Account successfully disconnected' => '',
    'Account updated' => 'A fiók frissítve',
    'Bind account' => 'Fiók hozzákötése',
    'Can not disconnect single authentication method. Please fill email and password and try again' => '',
    'Cancel' => 'Mégsem',
    'Changing your email requires email confirmation' => '',
    'Connected' => 'Kapcsolódva',
    'Create Time' => '',
    'Disconnect' => 'Kijelentkezés',
    'Full Name' => 'Teljes név',
    'Go home' => '',
    'Go to my account' => '',
    'Guests can not disconnect accounts' => '',
    'ID' => 'Azonosító',
    'Instructions to reset your password have been sent' => '',
    'Invalid key' => 'Key inválida',
    'Keychain' => '',
    'Language' => 'Nyelv',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => '',
    'Log in here' => 'Jelentkezzen be itt',
    'Login' => 'Bejelentkezés',
    'Password has been reset' => '',
    'Passwords do not match' => 'A jelszavak nem egyeznek',
    'Pending email confirmation: [ {newEmail} ]' => '',
    'Profile' => 'Profil',
    'Resend' => 'Újraküldés',
    'Reset' => '',
    'Start Page' => '',
    'Submit' => '',
    'This account has already been connected' => '',
    'Update' => 'Frissítés',
    'Update Time' => '',
    'User ID' => '',
    'Yii 2 User' => 'Yii 2 felhasználó',
    'Your email [ {email} ] has been confirmed' => '',
    'or' => 'vagy',
    '{attribute} can contain only letters, numbers, and "_"' => '',
    'Сan not disconnect a foreign account' => '',
];
