<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account has already been disabled' => '계정가 이미 비활성화되어 있습니다',
    'Account successfully disconnected' => '계정에 성공적으로 연결 해제되었습니다',
    'Account updated' => '계정 갱신',
    'Bind account' => '',
    'Can not disconnect single authentication method. Please fill email and password and try again' => '단일 인증 연결을 해제할 수 없습니다. 이메일과 비밀번호를 기입 후 다시 시도 바랍니다',
    'Cancel' => '취소',
    'Changing your email requires email confirmation' => '변경된 이메일의 확인이 필요합니다',
    'Connected' => '연결됨',
    'Create Time' => '생성 시각',
    'Disconnect' => '연결해제',
    'Full Name' => '이름',
    'Go home' => '홈페이지로 이동',
    'Go to my account' => '',
    'Guests can not disconnect accounts' => '손님은 계정 연결 해제를 할수 없습니다',
    'ID' => '아이디',
    'Instructions to reset your password have been sent' => '비밀번호 초기화 명령이 전송되었습니다',
    'Invalid key' => '잘못된 키',
    'Keychain' => '',
    'Language' => '언어',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => '현재 계정를 소셜네트워크 계정에 연결',
    'Log in here' => '로그인 되었습니다',
    'Login' => '로그인',
    'Password has been reset' => '비밀번호가 초기화 되었습니다',
    'Passwords do not match' => '비밀번호가 맞지 않습니다',
    'Pending email confirmation: [ {newEmail} ]' => '이메일이 승인되지 않았습니다: [ {newEmail} ]',
    'Profile' => '프로필',
    'Resend' => '재전송',
    'Reset' => '초기화',
    'Start Page' => '시작 페이지',
    'Submit' => '제출',
    'This account has already been connected' => '이 계정은 이미 연결 해제되었습니다',
    'Update' => '갱신',
    'Update Time' => '갱신 시각',
    'User ID' => '사용자 아이디',
    'Yii 2 User' => '',
    'Your email [ {email} ] has been confirmed' => '이메일이[{email} ] 확인 되었습니다',
    'or' => '또는',
    '{attribute} can contain only letters, numbers, and "_"' => '속성{attribute}값에는 문자, 숫자, "_"만 포함될 수 있습니다',
    'Сan not disconnect a foreign account' => '외부 계정 연결을 해제할수 없습니다',
];

